Update install_notes

diff --git a/install_notes b/install_notes
--- a/install_notes
+++ b/install_notes
@@ -223,12 +223,24 @@ DATA=$(echo "$localItem"|jq '.data'|egrep -v "^{|^}")
 DATA=$DATA`echo -e "\n  ,\"database\": \"$localDB\","`
 DATA=$DATA`echo -e "\n  \"docid\": \"$PAT\""`
 
-ESCOMMAND="curl -X PUT \"http://localhost:9200/altx_alllocal/$ESTYPE/$PAT?pretty\" -H 'Content-Type: application/json' -d'
+ESCOMMAND="curl -X PUT \"http://localhost:9200/altx_alllocal/$ESTYPE/$PAT?refresh=true&pretty\" -H 'Content-Type: application/json' -d'
 {
 $DATA
 }' "
 
-eval "$ESCOMMAND"
+commOutput=$(eval "$ESCOMMAND")
+if echo "$commOutput"|egrep "\"created\" : false|\"created\" : true" > /dev/null
+then
+        :
+else
+        echo "Failed during UPDATE or INSERT..."
+        global_comm_status=1
+        touch /home/local/CORP/vsaxena/DO_NOT_PROCEED
+        cmnd=$(echo "echo \"\$localItem\"|jq -r '.position'")
+        lastPos=$(eval "$cmnd")
+        echo "Exiting at $lastPos"
+        exit 1
+fi
 
 }
 
@@ -263,7 +275,7 @@ done
 
 sed "s/REPL_DB/$localDB/;s/REPL_TABLE/$localtbl/;s/REPL_TYPE/$ESTYPE/;s/REPL_WHERE/$WHERE_COND/;s/REPL_QRY/\'$localDB\' as \'database\',concat($pkcols) as docid,$colList/" logstash.template.update > logstash.conf
 
-../../logstash/bin/logstash -f logstash.conf
+$LOGSTASH -f logstash.conf
 
 }
 
@@ -286,13 +298,28 @@ do
         dataItem=$(eval "$cmnd"|sed "s/\"/'/g")
         PAT=$PAT`echo -e "$dataItem"`
 done
-eval "curl -XDELETE http://localhost:9200/altx_alllocal/$ESTYPE/$PAT"
+commOutput=$(eval "curl -XDELETE http://localhost:9200/altx_alllocal/$ESTYPE/$PAT?refresh=true")
+echo $?
+echo "$commOutput"
+if echo "$commOutput"|grep "{\"found\":true" > /dev/null
+then
+        :
+else
+        echo "Failed during DELETE..."
+        global_comm_status=1
+        touch /home/local/CORP/vsaxena/DO_NOT_PROCEED
+        cmnd=$(echo "echo \"\$localItem\"|jq -r '.position'")
+        lastPos=$(eval "$cmnd")
+        echo "Exiting at $lastPos"
+        exit 1
+fi
 }
 
 ####Main Starts here
 changeFile=$1
 ###extract for which database , table and type of event occured
-cat $changeFile|while read line
+global_comm_status=0
+while read line
 do
         DB=$(echo "$line"|jq -r '.database')
         evntype=$(echo "$line"|jq -r '.type')
@@ -310,14 +337,55 @@ do
                 echo "Processing update"
                 ### Use process_insert function if you want logstash to do the sync
                 process_insert_thru_curl "$DB" "$evntype" "$tbl" "$line"
-
         fi
 
         if [ $evntype = "delete" ]
         then
                 echo "Processing delete"
                 process_delete "$DB" "$evntype" "$tbl" "$line"
+
         fi
-done
+done <<< "$(cat $changeFile)"
+########################################################################
+echo "Sync Finished with status : $global_comm_status"
+if [ $global_comm_status -eq 0 ]
+then
+        mv $changeFile ${changeFile}.done
+fi
+########################################################################
 
 ===============================================================================================================================
+This script run_sync_to_elasticsearch.sh calls the above script 
+
+#!/bin/sh
+#### Proceed only if previous sync was successfull
+if [ -f /home/local/CORP/vsaxena/DO_NOT_PROCEED ]
+then
+        echo "Can't Proceed as previous sync did not succeed .."
+        exit 1
+fi
+##################################################################
+startPos=$1
+scriptdir=/home/local/CORP/vsaxena
+PAT=$(date +"%m%d%y%H%M%S")
+transactionFile=$scriptdir/${PAT}_mysql_changes
+MAXWELL=$scriptdir/maxwell-1.18.0/bin/maxwell
+echo "Collecting changes from maxwell ......"
+if [ ${#startPos} -eq 0 ]
+then
+        timeout 60 $MAXWELL --user='testuser'  --password='test123@=yhgf' --host=localhost --producer=file --output_file=$transactionFile --output_binlog_position
+else
+        echo "Staring with specified position ...$startPos"
+        timeout 60 $MAXWELL --user='testuser'  --password='test123@=yhgf' --host=localhost --producer=file --init_position="$startPos" --output_file=$transactionFile --output_binlog_position
+fi
+
+sleep 5
+echo "Now syncing elasticsearch.....with new changes"
+if [ -s $transactionFile ]
+then
+        outstr=$($scriptdir/update_data.sh $transactionFile 2>&1)
+        echo "$outstr"
+fi
+######################################################################################
+
+========================================================================================================================================
